In [24]:
import numpy as np

mat = np.zeros((3,3))

print(type(mat),mat, mat[1,1])

vec = np.ones((3))

print(5 * np.matmul(vec,mat), mat + mat)

import pandas as pd

df = pd.DataFrame({'col':[['a','b'],['a','c']]})

df.head(2)

#dic = {i:}

# for i in len(df):
#     for j in len(df):
#         mat[i,j] = 

<class 'numpy.ndarray'> [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 0.0
[0. 0. 0.] [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


col
0  [a, b]
1  [a, c]

In [13]:
df = pd.DataFrame({'col1':['a','a'], 'col2':['a','b']})

g = df['col1'].drop_duplicates()

print(g, df, type(df['col1']))

df[df['col2'] == 'b']

0    a
Name: col1, dtype: object   col1 col2
0    a    a
1    a    b <class 'pandas.core.series.Series'>


col1 col2
1    a    b

In [26]:
df = pd.DataFrame({'num':[1,2,3],"not_num":['a','b','c']})

df.sum(axis = 0)['num']

df = pd.DataFrame({'num1':[1,2,3], 'num2':[6,5,4]})

df1 = pd.DataFrame({'num':[4,4,4]})

print(df.sort_values('num2', ascending = False))

x = df.num1*df1.num

print(x,type(x))

x.sum()

   num1  num2
0     1     6
1     2     5
2     3     4
0     4
1     8
2    12
dtype: int64 <class 'pandas.core.series.Series'>


24

In [27]:
x = np.array([2]*4)

y = np.array([1]*4)

x - y


a = np.zeros((3,3))


np.delete(a,2,1)

array([[0., 0.],
       [0., 0.],
       [0., 0.]])